### ISSUE TITLE
open km alfred prompt to show macros only scoped to current active window

### ISSUE THREAD

**Issue by nikitavoloboev** [iansinnott/alfred-maestro#7]
Would it be possible to do? 

For example, I am in Safari, I trigger a script filter and it will only show me macros that are scoped to this application as well as global macros I have made.

Here is what I mean : 

![2016-09-19 at 18 16](https://cloud.githubusercontent.com/assets/6391776/18639699/34510060-7e95-11e6-8522-de918b5068d1.png)

I just want macros shown from this group and the global ones that I have. 

This would be very useful for me. Thank you.

**Comment by iansinnott** [comment]
Hm, I'm not entirely clear on what the issue is, but it might be that you need to enable "Alfred" as one of the applications this macro is available in _in addition to_ Safari. See #5 for a similar issue, and maybe [this section of the readme](https://github.com/iansinnott/alfred-maestro#application-specific-macro-groups) will help.

Please reopen this issue if that doesn't solve your problem
