### ISSUE TITLE
Possible to enable result caching to improve speed.

### ISSUE THREAD

**Issue by dunkarooftop** [iansinnott/alfred-maestro#9]
The macro in KM usually doesn't change that often, I am wondering for the next update is it possible to add "cache result" to improve the speed. Sometimes when I type too fast, the tiny lag cause triggering the wrong macro. Thanks for the great work, this is my most used Alfred workflow. :)

**Comment by iansinnott** [comment]
@dunkarooftop that's a really good point. When I built this I didn't consider caching at all. 

The script has multiple phases:
 
1. extract all macros from keyboard maestro
2. parse them
3. search them

Caching would probably make phase 1 and 2 considerably faster. I mention this because it's not clear to me where the bottleneck in performance is. It's also completely possible that sending the results to Alfred and having them re-rendered in a new list is what's slow, not this workflow itself.

I agree that caching would be a strong choice architecturally, but I'm not convinced it would have enough benefit for me to addressing it. However, I would welcome a PR :)

**Comment by maltsev** [comment]
@dunkarooftop the caching has been implemented in the latest release. You can install the new version by downloading and double-clicking _AlfredMaestro.alfredworkflow_ file from [the latest release page](https://github.com/iansinnott/alfred-maestro/releases/latest).
